services:
  mongodb:
    image: mongo:7
    container_name: product-mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: products
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: