from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.api_error import ApiError
from openapi_server import util

from openapi_server.models.api_error import ApiError  # noqa: E501

class ErrorResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error=None):  # noqa: E501
        """ErrorResponse - a model defined in OpenAPI

        :param error: The error of this ErrorResponse.  # noqa: E501
        :type error: ApiError
        """
        self.openapi_types = {
            'error': ApiError
        }

        self.attribute_map = {
            'error': 'error'
        }

        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorResponse of this ErrorResponse.  # noqa: E501
        :rtype: ErrorResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> ApiError:
        """Gets the error of this ErrorResponse.


        :return: The error of this ErrorResponse.
        :rtype: ApiError
        """
        return self._error

    @error.setter
    def error(self, error: ApiError):
        """Sets the error of this ErrorResponse.


        :param error: The error of this ErrorResponse.
        :type error: ApiError
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")  # noqa: E501

        self._error = error
