from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Product(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, description=None, price=None, stock=None, category=None, id=None, created_at=None, updated_at=None):  # noqa: E501
        """Product - a model defined in OpenAPI

        :param name: The name of this Product.  # noqa: E501
        :type name: str
        :param description: The description of this Product.  # noqa: E501
        :type description: str
        :param price: The price of this Product.  # noqa: E501
        :type price: float
        :param stock: The stock of this Product.  # noqa: E501
        :type stock: int
        :param category: The category of this Product.  # noqa: E501
        :type category: str
        :param id: The id of this Product.  # noqa: E501
        :type id: str
        :param created_at: The created_at of this Product.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this Product.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'name': str,
            'description': str,
            'price': float,
            'stock': int,
            'category': str,
            'id': str,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'price': 'price',
            'stock': 'stock',
            'category': 'category',
            'id': 'id',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }

        self._name = name
        self._description = description
        self._price = price
        self._stock = stock
        self._category = category
        self._id = id
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'Product':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Product of this Product.  # noqa: E501
        :rtype: Product
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Product.


        :return: The name of this Product.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Product.


        :param name: The name of this Product.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this Product.


        :return: The description of this Product.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Product.


        :param description: The description of this Product.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def price(self) -> float:
        """Gets the price of this Product.


        :return: The price of this Product.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this Product.


        :param price: The price of this Product.
        :type price: float
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501
        if price is not None and price < 0:  # noqa: E501
            raise ValueError("Invalid value for `price`, must be a value greater than or equal to `0`")  # noqa: E501

        self._price = price

    @property
    def stock(self) -> int:
        """Gets the stock of this Product.


        :return: The stock of this Product.
        :rtype: int
        """
        return self._stock

    @stock.setter
    def stock(self, stock: int):
        """Sets the stock of this Product.


        :param stock: The stock of this Product.
        :type stock: int
        """
        if stock is not None and stock < 0:  # noqa: E501
            raise ValueError("Invalid value for `stock`, must be a value greater than or equal to `0`")  # noqa: E501

        self._stock = stock

    @property
    def category(self) -> str:
        """Gets the category of this Product.


        :return: The category of this Product.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this Product.


        :param category: The category of this Product.
        :type category: str
        """
        if category is None:
            raise ValueError("Invalid value for `category`, must not be `None`")  # noqa: E501

        self._category = category

    @property
    def id(self) -> str:
        """Gets the id of this Product.


        :return: The id of this Product.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Product.


        :param id: The id of this Product.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this Product.


        :return: The created_at of this Product.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this Product.


        :param created_at: The created_at of this Product.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this Product.


        :return: The updated_at of this Product.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this Product.


        :param updated_at: The updated_at of this Product.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
