from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ProductDetail(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, description=None, price=None, stock=None, category=None):  # noqa: E501
        """ProductDetail - a model defined in OpenAPI

        :param id: The id of this ProductDetail.  # noqa: E501
        :type id: int
        :param name: The name of this ProductDetail.  # noqa: E501
        :type name: str
        :param description: The description of this ProductDetail.  # noqa: E501
        :type description: str
        :param price: The price of this ProductDetail.  # noqa: E501
        :type price: float
        :param stock: The stock of this ProductDetail.  # noqa: E501
        :type stock: int
        :param category: The category of this ProductDetail.  # noqa: E501
        :type category: str
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'description': str,
            'price': float,
            'stock': int,
            'category': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'price': 'price',
            'stock': 'stock',
            'category': 'category'
        }

        self._id = id
        self._name = name
        self._description = description
        self._price = price
        self._stock = stock
        self._category = category

    @classmethod
    def from_dict(cls, dikt) -> 'ProductDetail':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductDetail of this ProductDetail.  # noqa: E501
        :rtype: ProductDetail
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this ProductDetail.


        :return: The id of this ProductDetail.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ProductDetail.


        :param id: The id of this ProductDetail.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this ProductDetail.


        :return: The name of this ProductDetail.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ProductDetail.


        :param name: The name of this ProductDetail.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this ProductDetail.


        :return: The description of this ProductDetail.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ProductDetail.


        :param description: The description of this ProductDetail.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def price(self) -> float:
        """Gets the price of this ProductDetail.


        :return: The price of this ProductDetail.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this ProductDetail.


        :param price: The price of this ProductDetail.
        :type price: float
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def stock(self) -> int:
        """Gets the stock of this ProductDetail.


        :return: The stock of this ProductDetail.
        :rtype: int
        """
        return self._stock

    @stock.setter
    def stock(self, stock: int):
        """Sets the stock of this ProductDetail.


        :param stock: The stock of this ProductDetail.
        :type stock: int
        """
        if stock is None:
            raise ValueError("Invalid value for `stock`, must not be `None`")  # noqa: E501

        self._stock = stock

    @property
    def category(self) -> str:
        """Gets the category of this ProductDetail.


        :return: The category of this ProductDetail.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this ProductDetail.


        :param category: The category of this ProductDetail.
        :type category: str
        """
        if category is None:
            raise ValueError("Invalid value for `category`, must not be `None`")  # noqa: E501

        self._category = category
