from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.product import Product
from openapi_server.models.product_list_item_metadata import ProductListItemMetadata
from openapi_server import util

from openapi_server.models.product import Product  # noqa: E501
from openapi_server.models.product_list_item_metadata import ProductListItemMetadata  # noqa: E501

class ProductListItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None, metadata=None):  # noqa: E501
        """ProductListItem - a model defined in OpenAPI

        :param data: The data of this ProductListItem.  # noqa: E501
        :type data: List[Product]
        :param metadata: The metadata of this ProductListItem.  # noqa: E501
        :type metadata: ProductListItemMetadata
        """
        self.openapi_types = {
            'data': List[Product],
            'metadata': ProductListItemMetadata
        }

        self.attribute_map = {
            'data': 'data',
            'metadata': 'metadata'
        }

        self._data = data
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'ProductListItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductListItem of this ProductListItem.  # noqa: E501
        :rtype: ProductListItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[Product]:
        """Gets the data of this ProductListItem.


        :return: The data of this ProductListItem.
        :rtype: List[Product]
        """
        return self._data

    @data.setter
    def data(self, data: List[Product]):
        """Sets the data of this ProductListItem.


        :param data: The data of this ProductListItem.
        :type data: List[Product]
        """

        self._data = data

    @property
    def metadata(self) -> ProductListItemMetadata:
        """Gets the metadata of this ProductListItem.


        :return: The metadata of this ProductListItem.
        :rtype: ProductListItemMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: ProductListItemMetadata):
        """Sets the metadata of this ProductListItem.


        :param metadata: The metadata of this ProductListItem.
        :type metadata: ProductListItemMetadata
        """

        self._metadata = metadata
