from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ProductListItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, price=None, category=None):  # noqa: E501
        """ProductListItem - a model defined in OpenAPI

        :param id: The id of this ProductListItem.  # noqa: E501
        :type id: int
        :param name: The name of this ProductListItem.  # noqa: E501
        :type name: str
        :param price: The price of this ProductListItem.  # noqa: E501
        :type price: float
        :param category: The category of this ProductListItem.  # noqa: E501
        :type category: str
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'price': float,
            'category': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'price': 'price',
            'category': 'category'
        }

        self._id = id
        self._name = name
        self._price = price
        self._category = category

    @classmethod
    def from_dict(cls, dikt) -> 'ProductListItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductListItem of this ProductListItem.  # noqa: E501
        :rtype: ProductListItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this ProductListItem.


        :return: The id of this ProductListItem.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ProductListItem.


        :param id: The id of this ProductListItem.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this ProductListItem.


        :return: The name of this ProductListItem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ProductListItem.


        :param name: The name of this ProductListItem.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def price(self) -> float:
        """Gets the price of this ProductListItem.


        :return: The price of this ProductListItem.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this ProductListItem.


        :param price: The price of this ProductListItem.
        :type price: float
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def category(self) -> str:
        """Gets the category of this ProductListItem.


        :return: The category of this ProductListItem.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this ProductListItem.


        :param category: The category of this ProductListItem.
        :type category: str
        """
        if category is None:
            raise ValueError("Invalid value for `category`, must not be `None`")  # noqa: E501

        self._category = category
