from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.book_list_item import BookListItem
from openapi_server.models.books_get200_response_metadata import BooksGet200ResponseMetadata
from openapi_server import util

from openapi_server.models.book_list_item import BookListItem  # noqa: E501
from openapi_server.models.books_get200_response_metadata import BooksGet200ResponseMetadata  # noqa: E501

class BooksGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None, metadata=None):  # noqa: E501
        """BooksGet200Response - a model defined in OpenAPI

        :param data: The data of this BooksGet200Response.  # noqa: E501
        :type data: List[BookListItem]
        :param metadata: The metadata of this BooksGet200Response.  # noqa: E501
        :type metadata: BooksGet200ResponseMetadata
        """
        self.openapi_types = {
            'data': List[BookListItem],
            'metadata': BooksGet200ResponseMetadata
        }

        self.attribute_map = {
            'data': 'data',
            'metadata': 'metadata'
        }

        self._data = data
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'BooksGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _books_get_200_response of this BooksGet200Response.  # noqa: E501
        :rtype: BooksGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[BookListItem]:
        """Gets the data of this BooksGet200Response.


        :return: The data of this BooksGet200Response.
        :rtype: List[BookListItem]
        """
        return self._data

    @data.setter
    def data(self, data: List[BookListItem]):
        """Sets the data of this BooksGet200Response.


        :param data: The data of this BooksGet200Response.
        :type data: List[BookListItem]
        """

        self._data = data

    @property
    def metadata(self) -> BooksGet200ResponseMetadata:
        """Gets the metadata of this BooksGet200Response.


        :return: The metadata of this BooksGet200Response.
        :rtype: BooksGet200ResponseMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: BooksGet200ResponseMetadata):
        """Sets the metadata of this BooksGet200Response.


        :param metadata: The metadata of this BooksGet200Response.
        :type metadata: BooksGet200ResponseMetadata
        """

        self._metadata = metadata
