from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class BookDetail(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, title=None, author=None, category=None):  # noqa: E501
        """BookDetail - a model defined in OpenAPI

        :param id: The id of this BookDetail.  # noqa: E501
        :type id: int
        :param title: The title of this BookDetail.  # noqa: E501
        :type title: str
        :param author: The author of this BookDetail.  # noqa: E501
        :type author: str
        :param category: The category of this BookDetail.  # noqa: E501
        :type category: str
        """
        self.openapi_types = {
            'id': int,
            'title': str,
            'author': str,
            'category': str
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'author': 'author',
            'category': 'category'
        }

        self._id = id
        self._title = title
        self._author = author
        self._category = category

    @classmethod
    def from_dict(cls, dikt) -> 'BookDetail':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookDetail of this BookDetail.  # noqa: E501
        :rtype: BookDetail
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this BookDetail.


        :return: The id of this BookDetail.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this BookDetail.


        :param id: The id of this BookDetail.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this BookDetail.


        :return: The title of this BookDetail.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this BookDetail.


        :param title: The title of this BookDetail.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this BookDetail.


        :return: The author of this BookDetail.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this BookDetail.


        :param author: The author of this BookDetail.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def category(self) -> str:
        """Gets the category of this BookDetail.


        :return: The category of this BookDetail.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this BookDetail.


        :param category: The category of this BookDetail.
        :type category: str
        """
        if category is None:
            raise ValueError("Invalid value for `category`, must not be `None`")  # noqa: E501

        self._category = category
