from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.book_detail import BookDetail
from openapi_server import util

from openapi_server.models.book_detail import BookDetail  # noqa: E501

class BooksPost201Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """BooksPost201Response - a model defined in OpenAPI

        :param data: The data of this BooksPost201Response.  # noqa: E501
        :type data: BookDetail
        """
        self.openapi_types = {
            'data': BookDetail
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'BooksPost201Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _books_post_201_response of this BooksPost201Response.  # noqa: E501
        :rtype: BooksPost201Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> BookDetail:
        """Gets the data of this BooksPost201Response.


        :return: The data of this BooksPost201Response.
        :rtype: BookDetail
        """
        return self._data

    @data.setter
    def data(self, data: BookDetail):
        """Sets the data of this BooksPost201Response.


        :param data: The data of this BooksPost201Response.
        :type data: BookDetail
        """

        self._data = data
