from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class BooksGet200ResponseMetadata(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, page=None, limit=None, total=None):  # noqa: E501
        """BooksGet200ResponseMetadata - a model defined in OpenAPI

        :param page: The page of this BooksGet200ResponseMetadata.  # noqa: E501
        :type page: int
        :param limit: The limit of this BooksGet200ResponseMetadata.  # noqa: E501
        :type limit: int
        :param total: The total of this BooksGet200ResponseMetadata.  # noqa: E501
        :type total: int
        """
        self.openapi_types = {
            'page': int,
            'limit': int,
            'total': int
        }

        self.attribute_map = {
            'page': 'page',
            'limit': 'limit',
            'total': 'total'
        }

        self._page = page
        self._limit = limit
        self._total = total

    @classmethod
    def from_dict(cls, dikt) -> 'BooksGet200ResponseMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _books_get_200_response_metadata of this BooksGet200ResponseMetadata.  # noqa: E501
        :rtype: BooksGet200ResponseMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def page(self) -> int:
        """Gets the page of this BooksGet200ResponseMetadata.


        :return: The page of this BooksGet200ResponseMetadata.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this BooksGet200ResponseMetadata.


        :param page: The page of this BooksGet200ResponseMetadata.
        :type page: int
        """

        self._page = page

    @property
    def limit(self) -> int:
        """Gets the limit of this BooksGet200ResponseMetadata.


        :return: The limit of this BooksGet200ResponseMetadata.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit: int):
        """Sets the limit of this BooksGet200ResponseMetadata.


        :param limit: The limit of this BooksGet200ResponseMetadata.
        :type limit: int
        """

        self._limit = limit

    @property
    def total(self) -> int:
        """Gets the total of this BooksGet200ResponseMetadata.


        :return: The total of this BooksGet200ResponseMetadata.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this BooksGet200ResponseMetadata.


        :param total: The total of this BooksGet200ResponseMetadata.
        :type total: int
        """

        self._total = total
