from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ErrorError(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, message=None, details=None):  # noqa: E501
        """ErrorError - a model defined in OpenAPI

        :param code: The code of this ErrorError.  # noqa: E501
        :type code: int
        :param message: The message of this ErrorError.  # noqa: E501
        :type message: str
        :param details: The details of this ErrorError.  # noqa: E501
        :type details: str
        """
        self.openapi_types = {
            'code': int,
            'message': str,
            'details': str
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message',
            'details': 'details'
        }

        self._code = code
        self._message = message
        self._details = details

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Error_error of this ErrorError.  # noqa: E501
        :rtype: ErrorError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this ErrorError.


        :return: The code of this ErrorError.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this ErrorError.


        :param code: The code of this ErrorError.
        :type code: int
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this ErrorError.


        :return: The message of this ErrorError.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ErrorError.


        :param message: The message of this ErrorError.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def details(self) -> str:
        """Gets the details of this ErrorError.


        :return: The details of this ErrorError.
        :rtype: str
        """
        return self._details

    @details.setter
    def details(self, details: str):
        """Sets the details of this ErrorError.


        :param details: The details of this ErrorError.
        :type details: str
        """

        self._details = details
