# Connect DB
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=user
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Resilience4j Config
resilience4j.ratelimiter.instances.mainService.limit-for-period=10
resilience4j.ratelimiter.instances.mainService.limit-refresh-period=1s

resilience4j.ratelimiter.instances.mainService.timeout-duration=0

