emit:
  - "@typespec/openapi3"
  - "@azure-tools/typespec-python"

options:
  "@typespec/openapi3":
    output-file: "openapi.json"
  "@azure-tools/typespec-python":
    output-dir: "{project-root}/generated/python"
    package-name: "event_tracking_client"