# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# pylint: disable=useless-super-delegation

from typing import Any, Mapping, Optional, TYPE_CHECKING, overload

from .._utils.model_base import Model as _Model, rest_field

if TYPE_CHECKING:
    from .. import models as _models


class BookCreateRequest(_Model):
    """BookCreateRequest.

    :ivar title: Required.
    :vartype title: str
    :ivar author: Required.
    :vartype author: str
    :ivar category: Required.
    :vartype category: str
    """

    title: str = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""
    author: str = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""
    category: str = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""

    @overload
    def __init__(
        self,
        *,
        title: str,
        author: str,
        category: str,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class BookDetail(_Model):
    """BookDetail.

    :ivar id: Required.
    :vartype id: int
    :ivar title: Required.
    :vartype title: str
    :ivar author: Required.
    :vartype author: str
    :ivar category: Required.
    :vartype category: str
    """

    id: int = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""
    title: str = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""
    author: str = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""
    category: str = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""

    @overload
    def __init__(
        self,
        *,
        id: int,  # pylint: disable=redefined-builtin
        title: str,
        author: str,
        category: str,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class BookDetailResponse(_Model):
    """BookDetailResponse.

    :ivar data: Required.
    :vartype data: ~bookapi.models.BookDetail
    """

    data: "_models.BookDetail" = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""

    @overload
    def __init__(
        self,
        *,
        data: "_models.BookDetail",
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class BookListItem(_Model):
    """BookListItem.

    :ivar id: Required.
    :vartype id: int
    :ivar title: Required.
    :vartype title: str
    :ivar author: Required.
    :vartype author: str
    """

    id: int = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""
    title: str = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""
    author: str = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""

    @overload
    def __init__(
        self,
        *,
        id: int,  # pylint: disable=redefined-builtin
        title: str,
        author: str,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class BookListResponse(_Model):
    """BookListResponse.

    :ivar data: Required.
    :vartype data: list[~bookapi.models.BookListItem]
    :ivar metadata: Required.
    :vartype metadata: ~bookapi.models.PaginationMetadata
    """

    data: list["_models.BookListItem"] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""
    metadata: "_models.PaginationMetadata" = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""

    @overload
    def __init__(
        self,
        *,
        data: list["_models.BookListItem"],
        metadata: "_models.PaginationMetadata",
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class BookUpdateRequest(_Model):
    """BookUpdateRequest.

    :ivar title: Required.
    :vartype title: str
    :ivar author: Required.
    :vartype author: str
    :ivar category: Required.
    :vartype category: str
    """

    title: str = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""
    author: str = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""
    category: str = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""

    @overload
    def __init__(
        self,
        *,
        title: str,
        author: str,
        category: str,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class ErrorDetail(_Model):
    """ErrorDetail.

    :ivar code: Required.
    :vartype code: int
    :ivar message: Required.
    :vartype message: str
    :ivar details:
    :vartype details: str
    """

    code: int = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""
    message: str = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""
    details: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])

    @overload
    def __init__(
        self,
        *,
        code: int,
        message: str,
        details: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class ErrorResponse(_Model):
    """ErrorResponse.

    :ivar error: Required.
    :vartype error: ~bookapi.models.ErrorDetail
    """

    error: "_models.ErrorDetail" = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""

    @overload
    def __init__(
        self,
        *,
        error: "_models.ErrorDetail",
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class PaginationMetadata(_Model):
    """PaginationMetadata.

    :ivar page: Required.
    :vartype page: int
    :ivar limit: Required.
    :vartype limit: int
    :ivar total: Required.
    :vartype total: int
    """

    page: int = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""
    limit: int = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""
    total: int = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Required."""

    @overload
    def __init__(
        self,
        *,
        page: int,
        limit: int,
        total: int,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class RefreshTokenResponse(_Model):
    """RefreshTokenResponse.

    :ivar access_token: Required.
    :vartype access_token: str
    """

    access_token: str = rest_field(name="accessToken", visibility=["read", "create", "update", "delete", "query"])
    """Required."""

    @overload
    def __init__(
        self,
        *,
        access_token: str,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
